---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: Qwen PET Community Support
    url: https://github.com/JuanVilla424/qwen-pet/discussions
    about: Please ask and answer questions here.
  - name: Qwen PET Security Reports
    url: https://juanvilla424.github.io/qwen-pet/SECURITY
    about: Please report security vulnerabilities here.
